### ISSUE TITLE
Question: Primefaces 4 + jsfexportercore 1.0.2

### ISSUE THREAD

**Issue by edudebom** [rdicroce/jsfexporter#26]
i'm having this error: Could not find an IExportSource implementation for export source org.primefaces.component.treetable.TreeTable

p :treeTable value="#{estruturaProdutoMB.root}" 
                                     var="document"
                                     id="arvore"
                                     selection="#{estruturaProdutoMB.selectedNode}"
                                     emptyMessage="Nenhum registro encontrado"
                                     selectionMode="single">.../p:treeTable>

 p:commandButton value="Export" 
                                                 ajax="false">
                                    <l:dataExporter source="arvore"
                                                    fileType="excel" fileName="myfile"/>
                                /p:commandButton>

What i'm doing wrong ?

**Comment by nafnganef** [comment]
i have same problem, please share your solution, thanks.
