### ISSUE TITLE
PostProcess CSV Export

### ISSUE THREAD

**Issue by agriesbaum** [rdicroce/jsfexporter#34]
Hi,

I tried to use your lib for customizing my CSV Export. I need to remove the 'footerText' that is displayed in Primefaces p:dataTable. I could not find any documentation for writing such a Postprocessor.
Can you give me a hint how to realize this task?

P.S: I tried to find any mail address to write to but I did not find anything, sorry for using the Issue tool.

greetz

**Comment by rdicroce** [comment]
The post-processor can be any EL method that takes a single argument: the export context. The type of the export context object depends on the export type. For CSV, it is List < List < String > >.

Another way to accomplish this is to use f:param inside your commandButton/Link and then add a rendered attribute to your h:outputText, so it will only be rendered if that param is not passed in the request.
